//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllianceScouting
    {
        public long game_id { get; set; }
        public long team_id { get; set; }
        public string alliance_color { get; set; }
        public long rank { get; set; }
        public long id { get; set; }
        public string scouter_name { get; set; }
    }
}
