//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScouting
    {
        public int game_id { get; set; }
        public int red_score { get; set; }
        public int blue_score { get; set; }
    }
}
