//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitScoutingProps
    {
        public long prop_id { get; set; }
        public string prop_description { get; set; }
        public string prop_style { get; set; }
        public string prop_type { get; set; }
    }
}
