//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamScouting
    {
        public int game_id { get; set; }
        public int team_id { get; set; }
        public int prop_id { get; set; }
        public string prop_value { get; set; }
        public long id { get; set; }
    }
}
